### PR TITLE
[5-database-setup-mistake] database connection improved

### LINKED ISSUE #5: Database setup mistake
There's something that does not work in _connection.js_ if it fails to connect you just show a console error.
But if there's no connection better to have a fatal and block the run, or you risk the app will start but it will not work at all.

Also worth invest a bit to check if that is the proper way to connect to db, because it's like you keep a constant connection since the start of the app... but try to turn the database down and see what happens... and then try to turn that back on... and check

### PR DESCRIPTION
**Pull request by wojciechszmelczerczyk**
# Database connection
- When during database connection something go wrong, shut off application
-  Database connection is opened before every operation and close after

### CODE REVIEW

**Comment by matteocrippa** [comment]
@wojciechszmelczerczyk please provide a description of the changes, a PR with no description should be rejected

File: server/controllers/noteController.js [hunk 1]
```diff
@@ -29,22 +40,32 @@ const createNote = (req, res) => {
 
   // give response
   res.send("note added to database");
```
Comment (matteocrippa) [inline server/controllers/noteController.js]: why is returning a plain text?

File: server/controllers/noteController.js [hunk 2]
```diff
@@ -1,24 +1,35 @@
 const Note = require("../models/Note.js");
 const extractIdFromToken = require("../token/extractId.js");
+const { dbConnection, closeDbConnection } = require("../db/connection");
 
 const getAllNotes = async (req, res) => {
   // extract jwt id
   // use this id in query to find data correlated with user
 
+  await dbConnection();
```
Comment (matteocrippa) [inline server/controllers/noteController.js]: sure that is worth all the time, connect and disconnect from db?
mongoose is not able to take care automatically with an auto close in case of timeout?

File: server/db/connection.js [hunk 3]
```diff
@@ -4,11 +4,28 @@ const mongoose = require("mongoose");
...
+
+const dbConnection = async () => {
+  try {
+    await mongoose.connect(uri, {
+      useNewUrlParser: true,
+      useUnifiedTopology: true,
+    });
+  } catch (err) {
+    // if error occured kill process
+    process.exit(1);
```
Comment (matteocrippa) [inline server/db/connection.js:26]: I would add some info in the log why the app shut down

File: server/controllers/userController.js [hunk 4]
```diff
@@ -36,9 +42,10 @@ const authenticate = async (req, res) => {
     res.json({ error: err.message });
     return err;
   }
+  await closeDbConnection();
 };
 
-const logout = async (req, res) => {
+const logout = (req, res) => {
   res.cookie("jwt", "", {
```
Comment (matteocrippa) [inline server/controllers/userController.js:53]: you should invalidate the token in db too

**Review by matteocrippa — CHANGES_REQUESTED** [review]
I think there's some changes needed still
